# Generated by Django 2.2.6 on 2019-10-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20191023_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', 'TRADE_SUCCESS'), ('TRADE_CLOSED', 'TRADE_CLOSED'), ('PAYING', 'PAYING')], default='paying', max_length=30, verbose_name='pay_status'),
        ),
    ]
