# Generated by Django 2.2.6 on 2019-10-23 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='province')),
                ('city', models.CharField(default='', max_length=100, verbose_name='city')),
                ('district', models.CharField(default='', max_length=100, verbose_name='district')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='signer_name')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='signer_mobile')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'UserAddress',
                'verbose_name_plural': 'UserAddress',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'UserFav',
                'verbose_name_plural': 'UserFav',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'leave message'), (2, 'complain'), (3, 'consult'), (4, 'service'), (5, 'buy')], default=1, help_text='留言类型: 1(留言),2(投诉),3(询问),4(售后),5(求购)', verbose_name='留言类型')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='subject')),
                ('message', models.TextField(default='', help_text='message', verbose_name='message')),
                ('file', models.FileField(help_text='file', upload_to='message/images/', verbose_name='file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'UserLeavingMessage',
                'verbose_name_plural': 'UserLeavingMessage',
            },
        ),
    ]
